// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
/**
 * Persisted measurement order: fractional order keys + the canonical
 * comparator + the group-move planner.
 *
 * A measurement MAY carry an `orderKey` (persisted as `metadata.order_key`):
 * an ASCII base-36 string ordered by plain codepoint comparison. Keys are
 * generated by the reference fractional-indexing algorithm (integer part with
 * a self-delimiting length head + fraction that never ends in the minimum
 * digit), ported here to a base-36 digit set so key comparison is plain `<`
 * on the string. Rows without a key sort AFTER every keyed row, in creation
 * order — which is exactly the append-at-end semantic new measurements need,
 * so creation never generates keys; a document acquires keys lazily on its
 * first order-changing operation (see {@link planGroupMove}).
 */

const DIGITS = '0123456789abcdefghijklmnopqrstuvwxyz';
const SMALLEST_INTEGER = 'A' + DIGITS[0]!.repeat(26);

/* ── Reference fractional-indexing algorithm (base-36 digits) ─────────── */

/**
 * Midpoint of two fraction strings (`a` may be empty; `b` empty/undefined
 * means "no upper bound"). Never returns a string ending in the zero digit.
 */
function midpoint(a: string, b: string | null): string {
  const zero = DIGITS[0]!;
  if (b !== null && a >= b) throw new Error(`midpoint: ${a} >= ${b}`);
  if (a.slice(-1) === zero || (b && b.slice(-1) === zero)) {
    throw new Error('midpoint: trailing zero');
  }
  if (b) {
    // Strip the longest common prefix, padding `a` with zeros as we go.
    let n = 0;
    while ((a[n] || zero) === b[n]) n++;
    if (n > 0) return b.slice(0, n) + midpoint(a.slice(n), b.slice(n));
  }
  const digitA = a ? DIGITS.indexOf(a[0]!) : 0;
  const digitB = b ? DIGITS.indexOf(b[0]!) : DIGITS.length;
  if (digitB - digitA > 1) {
    return DIGITS[Math.round(0.5 * (digitA + digitB))]!;
  }
  // First digits are consecutive.
  if (b && b.length > 1) return b.slice(0, 1);
  // `b` is empty or a single digit: recurse into `a`'s tail with no upper
  // bound, e.g. midpoint('49', '5') = '4' + midpoint('9', null) = '495'.
  return DIGITS[digitA]! + midpoint(a.slice(1), null);
}

/** Integer-part length encoded by the head char: a..z ascending positive
 *  lengths, A..Z descending negative lengths (self-delimiting, so
 *  lexicographic order equals numeric order across lengths). */
function integerLength(head: string): number {
  if (head >= 'a' && head <= 'z') return head.charCodeAt(0) - 97 + 2;
  if (head >= 'A' && head <= 'Z') return 90 - head.charCodeAt(0) + 2;
  throw new Error(`invalid order key head: ${head}`);
}

function integerPart(key: string): string {
  const len = integerLength(key[0]!);
  if (len > key.length) throw new Error(`invalid order key: ${key}`);
  return key.slice(0, len);
}

export function validateOrderKey(key: string): void {
  if (key === SMALLEST_INTEGER) throw new Error(`invalid order key: ${key}`);
  const i = integerPart(key); // throws on a bad head / truncated key
  // Every char after the head must be a base-36 digit: a foreign char (e.g.
  // from corrupt persisted metadata) still codepoint-compares, but it breaks
  // the digit arithmetic midpoint/increment assume, so reject it here — this
  // is the sanitizer isValidOrderKey guards external data with.
  for (let c = 1; c < key.length; c++) {
    if (DIGITS.indexOf(key[c]!) === -1) {
      throw new Error(`invalid order key: ${key}`);
    }
  }
  const f = key.slice(i.length);
  if (f.slice(-1) === DIGITS[0]) throw new Error(`invalid order key: ${key}`);
}

/** True when `key` parses as a well-formed order key (used to sanitize
 *  server/local data before it reaches the generator). */
export function isValidOrderKey(key: unknown): key is string {
  if (typeof key !== 'string' || key.length === 0) return false;
  try {
    validateOrderKey(key);
    return true;
  } catch {
    return false;
  }
}

/** Next integer part, or null at the maximum. */
function incrementInteger(x: string): string | null {
  const head = x[0]!;
  const digs = x.slice(1).split('');
  let carry = true;
  for (let i = digs.length - 1; carry && i >= 0; i--) {
    const d = DIGITS.indexOf(digs[i]!) + 1;
    if (d === DIGITS.length) {
      digs[i] = DIGITS[0]!;
    } else {
      digs[i] = DIGITS[d]!;
      carry = false;
    }
  }
  if (carry) {
    if (head === 'Z') return 'a' + DIGITS[0];
    if (head === 'z') return null;
    const h = String.fromCharCode(head.charCodeAt(0) + 1);
    if (h > 'a') {
      digs.push(DIGITS[0]!); // positive integers grow with the head
    } else {
      digs.pop(); // negative integers shrink as the head rises
    }
    return h + digs.join('');
  }
  return head + digs.join('');
}

/** Previous integer part, or null at the minimum. */
function decrementInteger(x: string): string | null {
  const head = x[0]!;
  const digs = x.slice(1).split('');
  let borrow = true;
  for (let i = digs.length - 1; borrow && i >= 0; i--) {
    const d = DIGITS.indexOf(digs[i]!) - 1;
    if (d === -1) {
      digs[i] = DIGITS.slice(-1);
    } else {
      digs[i] = DIGITS[d]!;
      borrow = false;
    }
  }
  if (borrow) {
    if (head === 'a') return 'Z' + DIGITS.slice(-1);
    if (head === 'A') return null;
    const h = String.fromCharCode(head.charCodeAt(0) - 1);
    if (h < 'Z') {
      digs.push(DIGITS.slice(-1)); // negative integers grow as the head falls
    } else {
      digs.pop(); // positive integers shrink with the head
    }
    return h + digs.join('');
  }
  return head + digs.join('');
}

/**
 * A key strictly between `a` and `b` (null = unbounded on that side).
 * Requires `a < b` when both given; throws otherwise.
 */
export function generateKeyBetween(a: string | null, b: string | null): string {
  if (a !== null) validateOrderKey(a);
  if (b !== null) validateOrderKey(b);
  if (a !== null && b !== null && a >= b) {
    throw new Error(`generateKeyBetween: ${a} >= ${b}`);
  }
  if (a === null) {
    if (b === null) return 'a' + DIGITS[0];
    const ib = integerPart(b);
    const fb = b.slice(ib.length);
    if (ib === SMALLEST_INTEGER) return ib + midpoint('', fb);
    if (ib < b) return ib; // the bare integer sorts below b's fraction
    const res = decrementInteger(ib);
    if (res === null) throw new Error('generateKeyBetween: cannot go lower');
    return res;
  }
  if (b === null) {
    const ia = integerPart(a);
    const fa = a.slice(ia.length);
    const i = incrementInteger(ia);
    return i === null ? ia + midpoint(fa, null) : i;
  }
  const ia = integerPart(a);
  const fa = a.slice(ia.length);
  const ib = integerPart(b);
  const fb = b.slice(ib.length);
  if (ia === ib) return ia + midpoint(fa, fb);
  const i = incrementInteger(ia);
  if (i === null) throw new Error('generateKeyBetween: cannot go higher');
  if (i < b) return i;
  return ia + midpoint(fa, null);
}

/** `n` distinct ascending keys strictly between `a` and `b`. */
export function generateNKeysBetween(
  a: string | null,
  b: string | null,
  n: number,
): string[] {
  if (n === 0) return [];
  if (n === 1) return [generateKeyBetween(a, b)];
  if (b === null) {
    let c = generateKeyBetween(a, b);
    const result = [c];
    for (let i = 0; i < n - 1; i++) {
      c = generateKeyBetween(c, b);
      result.push(c);
    }
    return result;
  }
  if (a === null) {
    let c = generateKeyBetween(a, b);
    const result = [c];
    for (let i = 0; i < n - 1; i++) {
      c = generateKeyBetween(a, c);
      result.push(c);
    }
    result.reverse();
    return result;
  }
  const mid = Math.floor(n / 2);
  const c = generateKeyBetween(a, b);
  return [
    ...generateNKeysBetween(a, c, mid),
    c,
    ...generateNKeysBetween(c, b, n - mid - 1),
  ];
}

export type Rng = () => number;

/**
 * Like {@link generateKeyBetween} with random low-order digits appended, so
 * two clients inserting into the same gap concurrently do not mint identical
 * keys. Appending is order-safe only when the base key is not a prefix of
 * `b` (a prefix's extension could overshoot), so the base is regenerated
 * inside the gap until it isn't one; the final appended digit is never the
 * zero digit, preserving the no-trailing-zero invariant.
 */
export function generateJitteredKeyBetween(
  a: string | null,
  b: string | null,
  rng: Rng = Math.random,
): string {
  let key = generateKeyBetween(a, b);
  if (b !== null) {
    while (b.startsWith(key)) key = generateKeyBetween(key, b);
  }
  const d1 = DIGITS[Math.floor(rng() * DIGITS.length)]!;
  const d2 = DIGITS[Math.floor(rng() * DIGITS.length)]!;
  const d3 = DIGITS[1 + Math.floor(rng() * (DIGITS.length - 1))]!;
  return key + d1 + d2 + d3;
}

/* ── Canonical comparator ─────────────────────────────────────────────── */

/** The fields ordering needs; structurally satisfied by `Measurement`. */
export interface OrderableRow {
  id: string;
  serverId?: string;
  orderKey?: string;
  createdAt?: string;
}

function tie(a: OrderableRow, b: OrderableRow): number {
  const ca = a.createdAt ?? '';
  const cb = b.createdAt ?? '';
  if (ca < cb) return -1;
  if (ca > cb) return 1;
  const ia = a.serverId ?? a.id;
  const ib = b.serverId ?? b.id;
  if (ia < ib) return -1;
  if (ia > ib) return 1;
  return 0;
}

/**
 * The one ordering rule: keyed band first (by codepoint key order), then the
 * unkeyed band in creation order. Total and deterministic over any mix;
 * duplicate keys and missing createdAt degrade to the tie-break, never an
 * unstable sort. A fully keyless document sorts exactly as the pre-key
 * hydrate order (createdAt then serverId/id).
 */
export function compareMeasurements(a: OrderableRow, b: OrderableRow): number {
  if (a.orderKey && b.orderKey) {
    if (a.orderKey < b.orderKey) return -1;
    if (a.orderKey > b.orderKey) return 1;
    return tie(a, b);
  }
  if (a.orderKey && !b.orderKey) return -1;
  if (!a.orderKey && b.orderKey) return 1;
  return tie(a, b);
}

/** Non-mutating canonical sort. */
export function sortCanonical<T extends OrderableRow>(rows: T[]): T[] {
  return [...rows].sort(compareMeasurements);
}

/** Insert `row` at its canonical position (used by delete-undo restore). */
export function insertCanonical<T extends OrderableRow>(rows: T[], row: T): T[] {
  const idx = rows.findIndex((r) => compareMeasurements(row, r) < 0);
  if (idx === -1) return [...rows, row];
  return [...rows.slice(0, idx), row, ...rows.slice(idx)];
}

/* ── Group-move planner ───────────────────────────────────────────────── */

export interface OrderAssignment {
  id: string;
  orderKey: string;
}

export interface PlannableRow extends OrderableRow {
  group: string;
  page: number;
}

export interface GroupMovePlan<T extends PlannableRow> {
  /** The array in its new order with new group/keys applied. */
  rows: T[];
  /**
   * Phase 1 — ORDER-PRESERVING writes (lazy materialization / normalization
   * of keyless, duplicate, or inverted keys at their current positions), in
   * write order. Persisting any prefix of these leaves the visible order
   * unchanged on every client.
   */
  preserve: OrderAssignment[];
  /**
   * Phase 2 — ORDER-CHANGING writes: coalesced same-page group stragglers in
   * document order, then the moved row LAST. Each write is an individually
   * consistent placement; the move itself becomes visible atomically with
   * the final write.
   */
  move: OrderAssignment[];
  /** The moved row's post-phase-1 key (undo restores this, never `undefined`). */
  movedPreviousKey: string;
  movedNewKey: string;
}

/**
 * Group-only result: the target group has no member on the moved row's page,
 * so retargeting `group` needs no placement, no keys, no materialization —
 * the moved row's block stands alone on its page either way.
 */
export interface GroupOnlyPlan {
  groupOnly: true;
}

function isGroupOnly<T extends PlannableRow>(
  p: GroupMovePlan<T> | GroupOnlyPlan | null,
): p is GroupOnlyPlan {
  return p !== null && (p as GroupOnlyPlan).groupOnly === true;
}
export { isGroupOnly };

/**
 * Plan a cross-group move with persisted placement.
 *
 * The input array is treated as the current canonical visual order (canvas
 * paint order). Returns:
 *  - `null` when there is nothing to do (row missing, or already in the
 *    target group);
 *  - a {@link GroupOnlyPlan} when only the `group` field should change;
 *  - a full {@link GroupMovePlan} otherwise.
 *
 * Placement is PAGE-scoped: the moved row lands after the target group's
 * last member on its own page, because the canvas and the sidebar both
 * project the array per page — a document-wide anchor on another page would
 * reorder unseen pages while leaving the visible one mismatched. If the
 * target group's same-page members are not contiguous in the page
 * projection, they are coalesced into one run so the sidebar's flattened
 * grouping and the paint order agree after the move.
 */
/**
 * Phase-1 materialization, DOCUMENT-WIDE: give every row a key at its current
 * position without changing the visible order. Valid ascending skeleton →
 * keyless runs are gap-filled between their keyed neighbors; duplicates or
 * inversions (concurrent-move residue, corrupt data) fall back to re-keying
 * every row in place. Persisting any prefix of `preserve` (in order) leaves
 * the visible order unchanged on every client.
 */
export function materializeKeys<T extends OrderableRow>(
  rows: T[],
): { keyOf: Map<string, string>; preserve: OrderAssignment[] } {
  const keyOf = new Map<string, string>();
  for (const r of rows) {
    if (isValidOrderKey(r.orderKey)) keyOf.set(r.id, r.orderKey);
  }
  const preserve: OrderAssignment[] = [];

  let skeletonOk = true;
  let prevKey: string | null = null;
  for (const r of rows) {
    const k = keyOf.get(r.id);
    if (k === undefined) continue;
    if (prevKey !== null && k <= prevKey) {
      skeletonOk = false;
      break;
    }
    prevKey = k;
  }

  if (!skeletonOk) {
    const fresh = generateNKeysBetween(null, null, rows.length);
    rows.forEach((r, i) => {
      keyOf.set(r.id, fresh[i]!);
      preserve.push({ id: r.id, orderKey: fresh[i]! });
    });
  } else {
    // Fill each maximal keyless run between its keyed neighbors.
    let i = 0;
    while (i < rows.length) {
      if (keyOf.has(rows[i]!.id)) {
        i++;
        continue;
      }
      let j = i;
      while (j < rows.length && !keyOf.has(rows[j]!.id)) j++;
      const lo = i > 0 ? keyOf.get(rows[i - 1]!.id)! : null;
      const hi = j < rows.length ? keyOf.get(rows[j]!.id)! : null;
      const filled = generateNKeysBetween(lo, hi, j - i);
      for (let k = i; k < j; k++) {
        keyOf.set(rows[k]!.id, filled[k - i]!);
        preserve.push({ id: rows[k]!.id, orderKey: filled[k - i]! });
      }
      i = j;
    }
  }

  return { keyOf, preserve };
}

export function planGroupMove<T extends PlannableRow>(
  rows: T[],
  movedId: string,
  targetGroup: string,
  rng: Rng = Math.random,
): GroupMovePlan<T> | GroupOnlyPlan | null {
  const moved = rows.find((r) => r.id === movedId);
  if (!moved || moved.group === targetGroup) return null;

  const samePageTargets = rows.filter(
    (r) => r.id !== movedId && r.group === targetGroup && r.page === moved.page,
  );
  if (samePageTargets.length === 0) return { groupOnly: true };

  // ── Phase 1: materialize / normalize keys at current positions ──
  const { keyOf, preserve } = materializeKeys(rows);

  const movedPreviousKey = keyOf.get(movedId)!;

  // ── Compute the final order ──
  const without = rows.filter((r) => r.id !== movedId);
  const anchor = samePageTargets[samePageTargets.length - 1]!;

  // Page projection (moved row excluded): find the contiguous run of target-
  // group members ending at the anchor; earlier same-page members separated
  // from it by interlopers are stragglers to coalesce.
  const pageSeq = without.filter((r) => r.page === moved.page);
  const anchorPageIdx = pageSeq.findIndex((r) => r.id === anchor.id);
  let runStartPageIdx = anchorPageIdx;
  while (
    runStartPageIdx > 0 &&
    pageSeq[runStartPageIdx - 1]!.group === targetGroup
  ) {
    runStartPageIdx--;
  }
  const runStartId = pageSeq[runStartPageIdx]!.id;
  const stragglers = pageSeq
    .slice(0, runStartPageIdx)
    .filter((r) => r.group === targetGroup);
  const stragglerIds = new Set(stragglers.map((r) => r.id));

  // Final document order: stragglers pulled to just before the run start
  // (relative order kept), moved row inserted right after the anchor.
  const reordered: T[] = [];
  for (const r of without) {
    if (stragglerIds.has(r.id)) continue;
    if (r.id === runStartId) reordered.push(...stragglers);
    reordered.push(r);
    if (r.id === anchor.id) reordered.push({ ...moved, group: targetGroup });
  }

  // ── Phase 2: keys for the displaced rows from their final neighbors ──
  const displaced = new Set<string>([...stragglerIds, movedId]);
  const move: OrderAssignment[] = [];
  let movedNewKey = movedPreviousKey;
  for (let idx = 0; idx < reordered.length; idx++) {
    const r = reordered[idx]!;
    if (!displaced.has(r.id)) continue;
    const lo = idx > 0 ? keyOf.get(reordered[idx - 1]!.id)! : null;
    let hi: string | null = null;
    for (let k = idx + 1; k < reordered.length; k++) {
      const cand = reordered[k]!;
      if (!displaced.has(cand.id) || move.some((a) => a.id === cand.id)) {
        hi = keyOf.get(cand.id)!;
        break;
      }
    }
    const newKey = generateJitteredKeyBetween(lo, hi, rng);
    keyOf.set(r.id, newKey);
    if (r.id === movedId) {
      movedNewKey = newKey;
    } else {
      move.push({ id: r.id, orderKey: newKey });
    }
  }
  // The moved row's write goes LAST: the reorder becomes visible to other
  // clients atomically with this single write.
  move.push({ id: movedId, orderKey: movedNewKey });

  const finalRows = reordered.map((r) => {
    const k = keyOf.get(r.id);
    return k !== undefined && k !== r.orderKey ? { ...r, orderKey: k } : r;
  });

  return {
    rows: finalRows,
    preserve,
    move,
    movedPreviousKey,
    movedNewKey,
  };
}
